import { minorPractices } from './knowledge.js';
const MAJOR_NAMES=['The Fool','The Magician','The High Priestess','The Empress','The Emperor','The Hierophant','The Lovers','The Chariot','Strength','The Hermit','Wheel of Fortune','Justice','The Hanged Man','Death','Temperance','The Devil','The Tower','The Star','The Moon','The Sun','Judgement','The World'];
const MAJOR=[
['beginning','Air','new beginnings, trust, openness and the first step','recklessness, avoidance, hesitation or impulsive escape','Take one reversible step. Curiosity is useful; carelessness is not.','Do not use a new beginning merely to avoid finishing the old one.'],
['power','Air','will, skill, focused intention and using available tools','scattered energy, manipulation, bluffing or unused ability','Choose one intention and make your behavior match it.','Performance is not the same thing as capability.'],
['intuition','Water','intuition, mystery, patience and inner knowing','ignored intuition, hidden information or inner noise','Pause long enough to identify what information is actually missing.','Anxiety can impersonate intuition when evidence is thin.'],
['growth','Earth','creation, nurture, sensuality and abundance','overgiving, neglect, creative blockage or dependency','Put energy into what can genuinely grow.','Stop feeding what only consumes you.'],
['structure','Fire','structure, authority, boundaries and stability','rigidity, domination or control driven by insecurity','Create one clear boundary or structure that reduces chaos.','Control can be fear wearing armor.'],
['belief','Earth','tradition, teaching, institutions and shared values','rebellion, questioning convention or inherited rules that no longer fit','Know which rule you are following and why.','Do not trade one unquestioned belief for another.'],
['choice','Air','connection, alignment, intimacy and a values-based choice','misalignment, temptation, divided values or difficult choice','Choose according to values, not only appetite or fear of loss.','Chemistry cannot repair incompatible values.'],
['movement','Water','direction, determination, self-control and momentum','loss of direction, force without focus or competing motives','Choose the destination before applying more force.','Speed is not the same thing as progress.'],
['courage','Fire','courage, compassion, restraint and quiet power','self-doubt, insecurity, anger or depleted confidence','Use calm, consistent strength before loud strength.','Suppression is not the same thing as strength.'],
['wisdom','Earth','solitude, reflection, searching and earned wisdom','isolation, avoidance or retreat without resolution','Step back, decide what you learned, then deliberately return.','Solitude becomes avoidance when you never return with an answer.'],
['change','Fire','cycles, turning points, changing conditions and momentum','repeating patterns, resistance to change or poor timing','Identify what changed and adapt instead of replaying the old response.','A familiar pattern can still be a trap.'],
['truth','Air','truth, balance, consequence and accountability','denial, imbalance, unfairness or avoided consequence','Separate evidence from preference and deal with what is actually true.','Selective honesty still tilts the scales.'],
['pause','Water','pause, surrender, suspension and a new perspective','stalling, needless sacrifice, martyrdom or refusal to release','Pause only long enough to change perspective, then decide.','Do not romanticize being stuck.'],
['transformation','Water','ending, transformation, release and rebirth','stagnation, fear of ending or clinging to what is complete','Allow what has ended to actually end so energy can move again.','Holding on to what has ended can leave less room for what you need now.'],
['balance','Fire','balance, integration, healing and moderation','excess, impatience, instability or incompatible extremes','Reduce the extremes and combine only what genuinely works.','Too much of a good thing is still too much.'],
['attachment','Earth','attachment, desire, compulsion, shadow and material bondage','release, awareness, reclaimed power or confronting dependency','Name the attachment and the trigger that keeps renewing it.','The strongest prison may be the one you keep choosing.'],
['revelation','Fire','upheaval, revelation, collapse of false structure and sudden truth','avoided truth, delayed change or private upheaval','Protect what is real and let the false structure fall.','Do not rebuild the exact structure that just proved it cannot hold.'],
['hope','Air','hope, renewal, openness and inspiration','discouragement, disconnection or fragile faith','Take the smallest concrete action that makes possibility more real.','Hope needs participation, not worship.'],
['uncertainty','Water','uncertainty, dreams, subconscious influence and illusion','truth emerging, confusion clearing or fear easing','Slow down until you can separate observable facts from the story your mind is building.','Fear can manufacture evidence for itself.'],
['clarity','Fire','clarity, vitality, warmth, success and confidence','delayed joy, temporary clouds or depleted confidence','Move toward what becomes clearer in daylight and simpler when stated plainly.','Do not dim something healthy because chaos feels more familiar.'],
['awakening','Fire','awakening, reckoning, calling and renewal','self-doubt, avoidance or unfinished reckoning','Answer the life question that keeps returning in different disguises.','Refusing the call does not make the question disappear.'],
['completion','Earth','completion, integration, wholeness and closure','unfinished business, delay or incomplete closure','Finish the cycle before demanding the next beginning.','Completion may require releasing your identity as the person still struggling.']
];
const RANKS=['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'];
const SUITS={
 wands:{name:'Wands',element:'Fire',domain:'action, ambition, creativity, confidence and will',m:[['inspiration, potential and a new spark','blocked inspiration, false starts or depleted drive'],['planning, personal power and choosing a direction','fear of the unknown, poor planning or playing too small'],['expansion, foresight and early progress','delays, limited vision or obstacles to expansion'],['celebration, stability, belonging and a milestone','instability at home, private conflict or celebration delayed'],['competition, friction and conflicting agendas','conflict avoidance, inner tension or unproductive fighting'],['recognition, confidence and earned victory','ego, delayed recognition or confidence depending on applause'],['defense, conviction and holding your ground','exhaustion, defensiveness or giving up under pressure'],['speed, movement, communication and rapid progress','delays, scattered momentum or messages going sideways'],['resilience, boundaries and persistence after difficulty','fatigue, paranoia or being too guarded to move'],['burden, responsibility and carrying too much','overload, delegation needed or refusing to put something down'],['curiosity, enthusiasm and a message of possibility','immaturity, inconsistency or excitement without follow-through'],['bold pursuit, adventure and fast-moving passion','impulsiveness, volatility or charging without a plan'],['confidence, warmth, magnetism and independent creative power','jealousy, insecurity or confidence becoming performance'],['leadership, vision, enterprise and mature creative authority','arrogance, domination or vision without listening']]},
 cups:{name:'Cups',element:'Water',domain:'emotion, intimacy, intuition, relationships and inner experience',m:[['emotional opening, love, compassion and intuitive renewal','emotional blockage, withheld feeling or self-love running dry'],['mutual attraction, partnership, reciprocity and agreement','imbalance, disconnection or values no longer meeting'],['friendship, celebration, support and shared joy','overindulgence, gossip or a social bond that excludes honesty'],['apathy, contemplation and an offer being overlooked','renewed interest, restlessness or finally noticing an opportunity'],['grief, disappointment and focus on what was lost','acceptance, recovery or slowly seeing what remains'],['memory, innocence, kindness and the return of the past','being stuck in nostalgia, idealizing the past or needing adulthood'],['many options, fantasy, temptation and imagination','clarity after confusion, choosing realistically or overwhelm lifting'],['walking away, emotional maturity and seeking deeper meaning','fear of leaving, avoidance or returning to what no longer satisfies'],['contentment, pleasure and a wish nearing fulfillment','dissatisfaction, excess or getting what you wanted without feeling fulfilled'],['emotional fulfillment, family harmony, belonging and shared values','disharmony, unrealistic expectations or fractures beneath the image'],['emotional curiosity, sensitivity and an intuitive message','emotional immaturity, escapism or ignoring inner signals'],['romance, idealism, invitation and following the heart','moodiness, fantasy, disappointment or charm without substance'],['empathy, emotional maturity, intuition and compassionate boundaries','overgiving, emotional dependence or intuition clouded by attachment'],['emotional stability, diplomacy and calm mastery of feeling','emotional suppression, manipulation or calm used to avoid honesty']]},
 swords:{name:'Swords',element:'Air',domain:'thought, truth, communication, decisions, conflict and mental pressure',m:[['clarity, truth, breakthrough and a decisive idea','confusion, misinformation or a truth not yet fully grasped'],['stalemate, guarded choice and difficult balance','indecision breaking, overload or avoiding a necessary decision'],['heartbreak, separation, painful truth and grief','healing, forgiveness or pain being processed rather than denied'],['rest, retreat, recovery and mental stillness','burnout, restlessness or returning before recovery is complete'],['conflict, hollow victory and winning at a cost','reconciliation, remorse or recognizing a fight is not worth continuing'],['transition, moving on and carrying lessons forward','resistance to transition, unresolved baggage or a difficult return'],['strategy, discretion, acting alone and incomplete disclosure','confession, exposure, self-deception or a strategy becoming dishonest'],['restriction, fear, limited perspective and feeling trapped','release, new perspective or recognizing the prison is partly mental'],['anxiety, sleeplessness, rumination and fear magnified by thought','recovery, perspective returning or anxiety beginning to loosen'],['painful ending, collapse, betrayal or a cycle reaching its limit','survival, recovery or refusing to accept an ending that already happened'],['alertness, curiosity, truth-seeking and a message requiring scrutiny','gossip, defensiveness, poor communication or information without maturity'],['speed, ambition, directness and decisive intellectual action','recklessness, aggression or moving faster than the facts'],['discernment, independence, boundaries and clear communication','bitterness, coldness or truth used as a weapon'],['logic, authority, strategy and principled decision-making','rigidity, manipulation or intellect separated from humanity']]},
 pentacles:{name:'Pentacles',element:'Earth',domain:'money, work, health, home, resources, security and material reality',m:[['material opportunity, a practical beginning and something tangible to build','missed opportunity, poor planning or a shaky material foundation'],['juggling priorities, adaptability and managing changing demands','overcommitment, disorganization or priorities colliding'],['craftsmanship, collaboration, learning and quality work','poor teamwork, shortcuts or effort without shared standards'],['security, saving, control and protecting resources','possessiveness, fear of loss or loosening an unhealthy grip'],['hardship, insecurity, exclusion and material or physical strain','recovery, assistance becoming available or rebuilding stability'],['giving, receiving, generosity and fair exchange','strings attached, debt, inequality or generosity masking control'],['patience, assessment, investment and waiting for results','impatience, poor return or continuing to invest without evidence'],['skill-building, repetition, diligence and mastery through practice','perfectionism, boredom, shortcuts or work without purpose'],['independence, comfort, earned abundance and self-sufficiency','overwork, dependence or material comfort hiding isolation'],['legacy, family wealth, long-term security and durable systems','financial instability, family conflict or a legacy that does not hold'],['practical curiosity, study and a tangible new opportunity','procrastination, poor follow-through or wanting results without practice'],['reliability, routine, persistence and slow dependable progress','stagnation, stubbornness or routine becoming lifeless'],['practical care, grounded abundance and resourceful nurturing','self-neglect, material insecurity or caring for everyone except yourself'],['stewardship, prosperity, leadership and mature material competence','greed, status obsession or security becoming control']]}
};
function minorAdvice(suit,i){return minorPractices[suit][i]}
function minorShadow(suit){return {wands:'Watch for ego, urgency or burnout disguising itself as purpose.',cups:'Watch for projection, idealization or emotional avoidance.',swords:'Watch for rumination, defensiveness or a story outrunning the evidence.',pentacles:'Watch for scarcity thinking, overcontrol or measuring worth only materially.'}[suit]}
export const cards=MAJOR_NAMES.map((name,i)=>({id:i,type:'major',name,theme:MAJOR[i][0],element:MAJOR[i][1],upright:MAJOR[i][2],reversed:MAJOR[i][3],advice:MAJOR[i][4],shadow:MAJOR[i][5],rank:null,suit:null,suitName:null}));
let id=22;for(const [key,s] of Object.entries(SUITS)){s.m.forEach((pair,i)=>cards.push({id:id++,type:'minor',name:`${RANKS[i]} of ${s.name}`,theme:s.domain,element:s.element,upright:pair[0],reversed:pair[1],advice:minorAdvice(key,i),shadow:minorShadow(key),rank:RANKS[i],suit:key,suitName:s.name}))}
export const suits=SUITS;
export {spreads} from '../../../shared/spreads.js';
export const zodiacMajor={Aries:4,Taurus:5,Gemini:6,Cancer:7,Leo:8,Virgo:9,Libra:11,Scorpio:13,Sagittarius:14,Capricorn:15,Aquarius:17,Pisces:18};
