import test from 'node:test';
import assert from 'node:assert/strict';
import {createReviewService,reviewInput,reviewResult} from '../src/services/reviewService.js';
import {GET,POST,DELETE} from '../../api/router.js';
const a='a'.repeat(64),b='b'.repeat(64);
const draft={name:'Example',rating:4,comment:'A fictional review used only in an isolated unit test.',consent:true};
function fixture(){const rows=new Map(),counts=new Map();const project=r=>{if(!r)return null;const {_id,...rest}=r;return rest;};const query=value=>({select(fields){assert.equal(fields.includes('-_id'),true);return{lean:async()=>Array.isArray(value)?value.map(project):project(value)}}});const model={findById:id=>query(rows.get(id)),find:()=>({sort:()=>({skip:skip=>({limit:limit=>query([...rows.values()].slice(skip,skip+limit))})})}),aggregate:async()=>rows.size?[{count:rows.size,average:[...rows.values()].reduce((n,r)=>n+r.rating,0)/rows.size}]:[],findOneAndUpdate:({ _id },update)=>{const row={_id,...(rows.get(_id)||update.$setOnInsert),...update.$set};rows.set(_id,row);return query(row);},deleteOne:async({_id})=>rows.delete(_id)};const quota={findOneAndUpdate:async({_id})=>{const count=counts.get(_id)||0;if(count>=6)throw new Error('duplicate');counts.set(_id,count+1);return {used:count+1};}};return {rows,service:createReviewService({connect:async()=>true,model,quota})};}
test('review create/update/delete changes the real summary and isolates browser ownership',async()=>{const {service,rows}=fixture();await service.save(a,draft);await service.save(b,{...draft,name:'Second',rating:2});let list=await service.list(1);assert.equal(list.total,2);assert.equal(list.average,3);assert.ok(list.reviews.every(r=>!('_id'in r)));assert.equal(JSON.stringify(list).includes(a),false);assert.ok(list.reviews[0].publicId);const originalId=(await service.mine(a)).review.publicId;await service.save(a,{...draft,rating:5});assert.equal((await service.mine(a)).review.publicId,originalId);assert.equal((await service.list(1)).average,3.5);await service.remove(a);assert.equal((await service.mine(a)).review,null);assert.equal((await service.mine(b)).review.name,'Second');assert.equal(rows.size,1);});
test('reviews reject malformed ratings, absent public consent, spam fields and excessive comments',()=>{for(const change of [{rating:0},{rating:6},{rating:2.5},{rating:'5'},{consent:false},{website:'spam'},{comment:'x'.repeat(25001)},{name:''}])assert.equal(reviewInput.safeParse({...draft,...change}).success,false);assert.equal(reviewInput.safeParse({...draft,comment:'x'.repeat(25000)}).success,true);});
test('review limits and unavailable storage never report a false publication',async()=>{const {service}=fixture();for(let i=0;i<6;i++)await service.save(a,draft);assert.equal((await reviewResult(()=>service.save(a,draft))).status,429);await service.save(b,draft);const unavailable=createReviewService({connect:async()=>false});assert.equal((await reviewResult(()=>unavailable.save(a,draft))).status,503);});
test('public reads require no client identity while writes require identity and validation',async()=>{const get=await GET(new Request('http://localhost/api/router?route=reviews'));assert.notEqual(get.status,401);assert.equal(get.headers.get('cache-control'),'no-store');const post=await POST(new Request('http://localhost/api/router?route=reviews',{method:'POST',body:JSON.stringify(draft)}));assert.equal(post.status,401);const invalid=await POST(new Request('http://localhost/api/router?route=reviews',{method:'POST',headers:{'X-Shadow-Client':a},body:JSON.stringify({...draft,rating:8})}));assert.equal(invalid.status,400);const del=await DELETE(new Request('http://localhost/api/router?route=reviews/mine',{method:'DELETE'}));assert.equal(del.status,401);});
