export const siteOrigin='https://enterthefold.io';
export const pages={
 support:{path:'/support',label:'Support The Fold',title:'Support The Fold | Independent Creative Work',description:'Support the independent artwork, music and development behind The Fold. Discover ways to help this creative project grow.',heading:'Keep the magic growing.',text:'The Fold is an independent creative project by David Northrop. Thank you for supporting the artwork, music and care behind every reading.'},
 read:{path:'/',label:'Tarot Reading',title:'Online Tarot Readings & The Shadow Deck | The Fold',description:'Explore a personal tarot reading with The Fold’s 78-card Shadow Deck, daily horoscopes, birth charts and clear explanations of card meanings.',heading:'Online tarot readings with The Shadow Deck',text:'Bring a question, choose a spread and explore the meaning of your cards. The Fold combines a complete 78-card tarot deck with optional birth-chart and numerology details, explaining the symbolism in everyday language. Use your reading as a prompt for reflection and a thoughtful next step.'},
 daily:{path:'/daily-horoscopes',label:'Daily Horoscopes',title:'Daily Horoscopes & Personal Reflections | The Fold',description:'Read your daily horoscope and create a personal reflection using your situation, chosen focus and optional birth-chart details at The Fold.',heading:'Daily horoscopes connected to your day',text:'Explore a dated zodiac horoscope, then describe what is on your mind to create a personal interpretation. Choose the kind of help you need and discover a practical reflection question, a small next step and the details behind your reading.'},
 deck:{path:'/tarot-deck',label:'Full Deck · 78 Cards',title:'Explore All 78 Tarot Cards & Their Meanings | The Fold',description:'Browse all 78 cards in The Fold’s gothic Shadow Deck. Explore the Major and Minor Arcana, card artwork and tarot meanings.',heading:'Discover the complete 78-card tarot deck',text:'Explore the Major Arcana and the four suits of the Minor Arcana in The Fold’s Shadow Deck. Browse individual card artwork and meanings to learn how each card contributes to a tarot reading.'},
 natal:{path:'/birth-chart',label:'Birth Chart',title:'Birth Chart Calculator & Natal Astrology | The Fold',description:'Calculate your natal birth chart with your birth date, time and place. Explore planetary signs, Whole Sign houses and aspects with The Fold.',heading:'Understand your natal birth chart',text:'Use your birth date, time and birthplace to explore planetary positions, your rising sign, Whole Sign houses and aspects. Missing or approximate birth information is identified rather than guessed. Astrology is offered as symbolic reflection, not a prediction of certain outcomes.'},
 learn:{path:'/tarot-astrology-numerology',label:'Tarot, Astrology & Numerology',title:'Learn Tarot, Zodiac Signs & Numerology | The Fold',description:'Learn what tarot cards, zodiac signs and numerology numbers mean. Explore The Fold’s guides and connect symbolic themes to your own reflections.',heading:'Learn the meaning behind your reading',text:'Explore tarot symbolism, zodiac signs, astrology and numerology in plain language. Use these guides alongside your reading to understand the themes, consider your own circumstances and decide what is useful to you.'},
 reviews:{path:'/reviews',label:'Reviews',title:'Visitor Reviews & Star Ratings | The Fold',description:'Read visitor reviews of The Fold and share your experience with a star rating and a comment about your tarot or horoscope reading.',heading:'What visitors think of The Fold',text:'Read experiences shared by visitors and leave your own honest rating and comment. These are community submissions, not verified purchases. Your public review is separate from your private reading and birth details.'}
};
export function tabFromLocation(location){if(location.hash==='#daily-horoscopes')return 'daily';if(location.hash==='#reviews')return 'reviews';if(location.pathname.replace(/\/$/,'')==='/history')return 'history';return Object.entries(pages).find(([,p])=>p.path=== (location.pathname.replace(/\/$/,'')||'/'))?.[0]||'read';}
export function applyPageMetadata(tab){const page=pages[tab]||pages.read;document.title=tab==='history'?'Your Past Readings | The Fold':page.title;for(const [selector,value] of [['meta[name="description"]',page.description],['meta[property="og:title"]',page.title],['meta[property="og:description"]',page.description],['meta[property="og:url"]',siteOrigin+page.path],['meta[name="twitter:title"]',page.title],['meta[name="twitter:description"]',page.description],['meta[name="robots"]',tab==='history'?'noindex, nofollow':'index, follow']])document.querySelector(selector)?.setAttribute('content',value);document.querySelector('link[rel="canonical"]')?.setAttribute('href',siteOrigin+page.path);}
