import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api.js';
import './CollectorPanel.css';
const call=(path,body)=>api(`/api/collectors/${path}`,body?{method:'POST',body:JSON.stringify(body)}:{});
export default function CollectorPanel({mode,active,onActiveChange,onSelect,busy,control,onAvailability,onAccountChange}){
 const [status,setStatus]=useState(null),[user,setUser]=useState(null),[wallets,setWallets]=useState([]),[cards,setCards]=useState([]),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false);
 const [expanded,setExpanded]=useState(new URLSearchParams(location.search).has('collector')),[authMode,setAuthMode]=useState('login'),[pending,setPending]=useState(false),[error,setError]=useState(''),[recovery,setRecovery]=useState('');
 const mounted=useRef(true),operation=useRef(false),pendingIds=useRef({}),epoch=useRef(0),currentUser=useRef(null);
 currentUser.current=user?.id;
 const edition=status?.editions.find(e=>e.mode===mode),credits=wallets.find(w=>w.edition===edition?.id)?.credits||0;
 const refresh=async()=>{const version=epoch.current;const [s,m]=await Promise.all([call('status'),call('me')]);if(mounted.current&&version===epoch.current){setStatus(s);setUser(m.user);setWallets(m.wallets);}};
 const list=async(next=1)=>{const owner=currentUser.current;const version=epoch.current;const result=await call(`collection?page=${next}`);if(mounted.current&&owner===currentUser.current&&version===epoch.current){setCards(result.cards);setPage(result.page);setHasMore(result.hasMore);}};
 useEffect(()=>{mounted.current=true;refresh().catch(()=>{if(mounted.current)setError('The collection is temporarily unavailable.');});return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!new URLSearchParams(location.search).has('collector'))return;let count=0;const timer=setInterval(()=>{refresh().catch(()=>{});if(++count>=5)clearInterval(timer);},3000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{onAccountChange();},[user?.id,onAccountChange]);
 useEffect(()=>{if(user)list().catch(()=>setError('Your collection could not be loaded. Please refresh.'));else setCards([]);},[user?.id]);
 useEffect(()=>{onAvailability({allowed:Boolean(user&&edition&&credits>0&&edition.remaining>0&&!pending),soldOut:Boolean(edition&&edition.remaining===0)});},[user,edition?.id,edition?.remaining,credits,pending,onAvailability]);
 function requestId(kind){const key=`fold-${kind}-${user.id}-${edition.id}`;let id=pendingIds.current[key];try{id=id||localStorage.getItem(key);}catch{}if(!id){id=crypto.randomUUID();pendingIds.current[key]=id;try{localStorage.setItem(key,id);}catch{}}return {key,id};}
 function clearId(key){delete pendingIds.current[key];try{localStorage.removeItem(key);}catch{}}
 control.current={draw:async()=>{
  if(!user||!edition)throw Error('Sign in to a collector profile and choose an edition first.');
  const {key,id}=requestId('draw');
  const result=await call('draw',{edition:edition.id,requestId:id});clearId(key);
  await Promise.allSettled([refresh(),list()]);return result.card;
 }};
 useEffect(()=>{if(!active)return;const update=()=>{if(document.visibilityState==='visible'&&!operation.current)refresh().catch(()=>{});};const timer=setInterval(update,30000);document.addEventListener('visibilitychange',update);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',update);};},[active]);
 const authenticate=async event=>{
  event.preventDefault();if(operation.current)return;epoch.current++;operation.current=true;setPending(true);setError('');
  const data=Object.fromEntries(new FormData(event.currentTarget));
  try{const r=await call(authMode,data);if(mounted.current){setUser(r.user);setRecovery(r.recoveryCode||'');}await refresh();}
  catch(e){if(mounted.current)setError(e.message);}finally{operation.current=false;if(mounted.current)setPending(false);}
 };
 const buy=async()=>{
  if(operation.current)return;operation.current=true;setPending(true);setError('');
  const {key,id}=requestId('purchase');
  try{const r=await call('checkout',{edition:edition.id,requestId:id});if(r.paid){clearId(key);await refresh();setError('Your previous pack is ready. Press Get 10 draws again if you want another pack.');}else{const url=new URL(r.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw Error('Checkout could not be opened.');location.assign(url.href);}}
  catch(e){if(e.status===409&&/expired/.test(e.message))clearId(key);setError(e.message);}finally{operation.current=false;if(mounted.current)setPending(false);}
 };
 const logout=async()=>{if(operation.current)return;epoch.current++;operation.current=true;setPending(true);try{await call('logout',{});setUser(null);setWallets([]);setCards([]);setRecovery('');onActiveChange(false);}catch(e){setError(e.message);}finally{operation.current=false;setPending(false);}};
 return <section className="collector-panel" aria-label="Collector’s edition">
  <div className="collector-bar"><button type="button" className="collector-switch" role="switch" aria-checked={active} disabled={busy||pending} onClick={()=>onActiveChange(!active)}>Collector’s Edition <span>{active?'On':'Off'}</span></button><button type="button" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded} aria-controls="collector-profile">{user?`${user.username} · My collection`:'My collector profile'}</button></div>
  {active&&<div className="collector-intro"><p>One original issue. Yours to keep.</p><span>{edition?`${edition.label} · ${credits} draws available`:'The first limited edition is being prepared.'}</span>{!status?.paymentsEnabled&&<p className="collector-note">$5 packs of 10 draws are coming soon. Checkout is not open yet.</p>}{status?.testMode&&<p className="collector-note">Test checkout only · No live purchases</p>}{!user&&<button type="button" onClick={()=>setExpanded(true)}>Sign in to collect</button>}{user&&<button type="button" className="collector-buy" disabled={busy||pending||!status?.paymentsEnabled||!edition||edition.packsAvailable<1} onClick={buy}>{pending?'Opening checkout…':'$5 · Get 10 draws'}</button>}<details className="collector-rules"><summary>About this collection</summary><p>Each mode has its own edition and draws. Every issued card stays in your profile and leaves the shared deck permanently. Each edition contains four jokers, each adding three draws. A joker uses one draw. Cards and draws cannot be exchanged for cash. Every card uses the collection’s shared artwork and has a unique number and complete message.</p><p>Draws do not expire. If all packs are reserved, sales pause while existing buyers can keep drawing. New editions have separate stock.</p></details></div>}
  {expanded&&<div id="collector-profile" className="collector-profile"><h2>My collection</h2>{!user?<><p>Keep your cards and unused draws together, even on another device.</p><form onSubmit={authenticate}><label>Collector username<input name="username" autoComplete="username" required pattern="[A-Za-z0-9_-]{3,32}" minLength={3} maxLength={32}/></label><label>{authMode==='recover'?'New password':'Password'}<input name="password" type="password" autoComplete={authMode==='login'?'current-password':'new-password'} required minLength={12} maxLength={128}/></label>{authMode==='recover'&&<label>Recovery key<input name="recoveryCode" required autoComplete="off"/></label>}<button disabled={pending||busy}>{pending?'Please wait…':authMode==='register'?'Create collector profile':authMode==='recover'?'Recover profile':'Sign in'}</button></form><div className="collector-auth-links">{['login','register','recover'].filter(x=>x!==authMode).map(x=><button key={x} type="button" disabled={pending} onClick={()=>{setAuthMode(x);setError('');}}>{x==='login'?'Sign in':x==='register'?'Create profile':'Forgot password?'}</button>)}</div></>:<><p>Signed in as <strong>{user.username}</strong>. Your cards stay here when you leave.</p>{recovery&&<div className="collector-recovery"><strong>Save your recovery key somewhere private.</strong><p>You’ll need it if you forget your password. It is shown only now.</p><code>{recovery}</code><button onClick={()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([`The Fold collector: ${user.username}\nRecovery key: ${recovery}\nKeep this private.\n`],{type:'text/plain'}));a.href=url;a.download='the-fold-recovery-key.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Save recovery key</button></div>}<div className="collector-balances">{wallets.map(w=><span key={w.edition}>{w.edition}: {w.credits} draws</span>)}</div>{cards.length?<div className="collector-grid">{cards.map(card=><button key={card.id} className="collector-owned" disabled={busy} onClick={()=>onSelect(card)}><small>LIMITED EDITION · {card.serial}</small><strong>{card.joker?'✦ Joker · ':''}{card.title}</strong><span>{card.message}</span><em>View & save card</em></button>)}</div>:<p>Your collection is waiting for its first card.</p>}<div className="collector-pagination"><button disabled={page===1||pending} onClick={()=>list(page-1).catch(e=>setError(e.message))}>Previous</button><span>Page {page}</span><button disabled={!hasMore||pending} onClick={()=>list(page+1).catch(e=>setError(e.message))}>Next</button></div><button type="button" disabled={pending||busy} onClick={logout}>Sign out</button></> }</div>}
  {error&&<p role="alert" className="collector-error">{error} <button type="button" onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh</button></p>}
 </section>;
}
