import { useState } from 'react';
import { signs, houses, planetThemes as functions, aspectLessons as aspectMeaning } from '../../../server/src/tarot/knowledge.js';
export function placementMeaning(planet) {
 const sign=signs[planet.signIndex];
 return `${planet.name} represents ${functions[planet.name]}. In ${sign.name}, the symbolic style emphasizes ${sign.theme}; house ${planet.house} brings that theme into ${houses[planet.house-1].toLowerCase()}. ${sign.practice} ${planet.motion==='Retrograde'?'Retrograde means apparent backward motion from Earth, not a flaw. In this tradition it can invite a more inward or revisiting approach to that theme.':planet.motion==='Stationary'?'Its apparent motion is near a turning point under the displayed threshold; treat the timing detail with care.':''}`;
}
export default function NatalChart({chart}) {
 const [selected,setSelected]=useState('Sun');
 if(!chart||chart.status==='not_requested') return <p className="muted">Enable your natal chart and enter birth details to calculate it here.</p>;
 if(chart.status!=='ready') return <p className="notice-banner" role="status">{chart.message}</p>;
 const current=chart.planets.find(p=>p.name===selected)||chart.planets[0],sun=chart.planets[0],moon=chart.planets[1];
 const point=(longitude,radius)=>{const a=(180+chart.angles.ascendant.longitude-longitude)*Math.PI/180;return [250+radius*Math.cos(a),250+radius*Math.sin(a)];};
 const markerPositions=[];
 for(const planet of chart.planets) {
  const candidates=[0,-6,6,-12,12].flatMap(offset=>[164,140,116,92].map(radius=>point(planet.longitude+offset,radius)));
  const pos=candidates.find(candidate=>markerPositions.every(other=>Math.hypot(candidate[0]-other[0],candidate[1]-other[1])>=25))||candidates.at(-1);
  markerPositions.push(pos);
 }
 return <section className="natal-chart" aria-label="Natal birth chart">
 <div className="section-kicker">The sky at your birth</div><h2>Your Natal Chart</h2>
 <p>{chart.localTime} · {chart.place}<br/><small>{chart.timeZone} · UTC{chart.offset} · {chart.zodiac} zodiac · {chart.houseSystem} houses</small></p>
 {chart.timeAccuracy==='approximate'&&<p className="notice-banner">You entered an approximate time. Rising sign, angles and houses may change with a more accurate time.</p>}
 <div className="natal-big-three">{[['Sun',sun.label,'Your conscious direction'],['Moon',moon.label,'Your emotional needs'],['Rising',chart.angles.ascendant.label,'Your approach to new situations']].map(([name,label,text])=><article key={name}><small>{name}</small><h3>{label}</h3><p>{text}</p></article>)}</div>
 <div className="natal-wheel-layout">
 <svg className="natal-wheel" viewBox="0 0 500 500" role="img" aria-label={`Tropical Whole Sign natal chart. Sun ${sun.label}, Moon ${moon.label}, rising ${chart.angles.ascendant.label}. Exact positions are listed below.`}>
 <circle cx="250" cy="250" r="242" fill="#100b1b" stroke="#be985b"/><circle cx="250" cy="250" r="196" fill="none" stroke="#886344"/><circle cx="250" cy="250" r="110" fill="none" stroke="#604661"/>
 {signs.map((sign,i)=>{const a=point(i*30,196),b=point(i*30,242),c=point(i*30+15,218);return <g key={sign.name}><line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke="#be985b"/><text x={c[0]} y={c[1]} textAnchor="middle" dominantBaseline="central" fill="#e8cf9d" fontSize="26" fontFamily="Georgia, serif">{sign.symbol}{'\uFE0E'}</text></g>;})}
 {chart.houses.map(h=>{const a=point(h.longitude,110),b=point(h.longitude,196),c=point(h.longitude+15,183);return <g key={h.number}><line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke="#554052"/><text x={c[0]} y={c[1]} textAnchor="middle" fill="#ad94b6" fontSize="12">{h.number}</text></g>;})}
 {chart.aspects.filter(a=>a.a===current.name||a.b===current.name).map(a=>{const p=point(chart.planets.find(p=>p.name===a.a).longitude,108),q=point(chart.planets.find(p=>p.name===a.b).longitude,108);return <line key={a.a+a.b+a.name} x1={p[0]} y1={p[1]} x2={q[0]} y2={q[1]} stroke={['Square','Opposition'].includes(a.name)?'#be849c':'#ab9b68'} opacity=".6"/>;})}
 {chart.planets.map((p,i)=>{const pos=markerPositions[i],tick=point(p.longitude,196);return <g key={p.name}><title>{p.name} · {p.label}</title><line x1={pos[0]} y1={pos[1]} x2={tick[0]} y2={tick[1]} stroke="#8a6d6c"/><circle cx={pos[0]} cy={pos[1]} r="11" fill={p.name===current.name?'#d5ad66':'#20152b'} stroke="#d5ad66"/><text x={pos[0]} y={pos[1]} textAnchor="middle" dominantBaseline="central" fill={p.name===current.name?'#100b1b':'#f1dec0'} fontSize="11">{i+1}</text></g>;})}
 </svg>
 <div><h3>Explore a placement</h3><p>Choose a planet to highlight its connections and read what its sign and house mean together.</p><div className="guide-tabs planet-buttons">{chart.planets.map((p,i)=><button key={p.name} aria-pressed={current.name===p.name} className={current.name===p.name?'active':''} onClick={()=>setSelected(p.name)}>{i+1}. {p.name}</button>)}</div><article className="knowledge-card"><h3>{current.name} · {current.label}</h3><p>{placementMeaning(current)}</p><small>House {current.house} · {current.motion}</small></article></div>
 </div>
 <details className="chart-details" open><summary>All planetary positions</summary><div className="chart-table-wrap"><table><thead><tr><th>Body</th><th>Position</th><th>House</th><th>Motion</th></tr></thead><tbody>{chart.planets.map(p=><tr key={p.name}><th scope="row">{p.name}</th><td>{p.label}</td><td>{p.house}</td><td>{p.motion}</td></tr>)}</tbody></table></div></details>
 <details className="chart-details"><summary>Angles & the twelve houses</summary><div className="knowledge-grid">{Object.entries({Ascendant:chart.angles.ascendant,Midheaven:chart.angles.midheaven,Descendant:chart.angles.descendant,'Imum Coeli':chart.angles.imumCoeli}).map(([name,p])=><article className="knowledge-card" key={name}><h3>{name}</h3><p>{p.label}</p></article>)}</div><p>Ascendant: eastern horizon and approach. Descendant: western horizon and partnership. Midheaven: meridian and public direction. Imum Coeli: the opposite meridian point and private foundations.</p><div className="knowledge-grid">{chart.houses.map(h=><article className="knowledge-card" key={h.number}><h3>House {h.number} · {h.sign}</h3><p>{h.meaning}</p><small>Cusp {h.label} · {chart.planets.filter(p=>p.house===h.number).map(p=>p.name).join(', ')||'No planets here; an empty house is not a missing part of life.'}</small></article>)}</div></details>
 <details className="chart-details"><summary>Major aspects · {chart.aspects.length} connections</summary><p>An aspect is the angular relationship between two planets. “Orb” is the distance from the exact angle: a smaller orb is a closer match. These are symbolic relationships, not predictions of particular events.</p><div className="knowledge-grid">{chart.aspects.map(a=><article className="knowledge-card" key={a.a+a.b+a.name}><h3>{a.a} {a.name.toLowerCase()} {a.b}</h3><small>{a.angle}° aspect · orb {a.orb.toFixed(2)}°</small><p>{a.a} describes {functions[a.a]}. {a.b} describes {functions[a.b]}. {aspectMeaning[a.name]}</p></article>)}</div>{!chart.aspects.length&&<p>No major aspects fall within the chosen orbs. The other chart placements remain available to explore.</p>}</details>
 <details className="chart-details"><summary>How this chart was calculated</summary><p>{chart.note}</p><p>Birth instant: {chart.utc}. Coordinates: {chart.latitude}, {chart.longitude}. Apparent daily motion is measured across one day; less than 0.003° per day is labeled stationary. Aspect orbs: conjunction/opposition 6° (8° with Sun or Moon); square/trine 6°; sextile 4°.</p><p>Calculated with <a href="https://github.com/cosinekitty/astronomy" target="_blank" rel="noreferrer">Astronomy Engine</a>. Historical civil-time offsets come from the runtime’s IANA time-zone data via Temporal. Different ephemerides and house systems may give slightly different results. Minor bodies, lunar nodes and current transits are not part of this natal chart.</p></details>
 <p className="reality-check">The sky positions are astronomical calculations. Their astrological meanings are symbolic interpretations, not scientifically established descriptions of personality or destiny.</p>
 </section>;
}
