import {useEffect,useState} from 'react';
import {api} from '../lib/api.js';
const empty={name:'',rating:0,comment:'',consent:false,website:''};
function Stars({rating}){return <span className="review-stars" aria-label={`${rating} out of 5 stars`}>{Array.from({length:5},(_,i)=><span key={i} aria-hidden="true" className={i<Math.round(rating)?'lit':''}>★</span>)}</span>;}
export default function Reviews(){
 const [form,setForm]=useState(empty),[data,setData]=useState(null),[mine,setMine]=useState(null),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(0),[confirmDelete,setConfirmDelete]=useState(false),[identityReady,setIdentityReady]=useState(false);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');api('/api/reviews?page='+page,{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[page,revision]);
 useEffect(()=>{if(identityReady)return;const controller=new AbortController();api('/api/reviews/mine',{signal:controller.signal}).then(result=>{setMine(result.review);if(result.review)setForm({...empty,...result.review,consent:false});setIdentityReady(true);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[revision,identityReady]);
 const change=e=>setForm(f=>({...f,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const result=await api('/api/reviews',{method:'POST',body:JSON.stringify(form)});setMine(result.review);setMessage('Your review is published. Thank you for sharing your experience.');setPage(1);setRevision(x=>x+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const remove=async()=>{setBusy(true);setError('');try{await api('/api/reviews/mine',{method:'DELETE'});setMine(null);setForm(empty);setConfirmDelete(false);setMessage('Your review has been removed.');setPage(1);setRevision(x=>x+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="panel reviews-panel" aria-labelledby="reviews-title"><p className="section-kicker">Voices from The Fold</p><h2 id="reviews-title">Visitor reviews</h2><p>Did your reading help you see something more clearly? Share an honest experience with the next person stepping into The Fold.</p>
 {data&&<div className="review-summary">{data.total?<><strong>{data.average.toFixed(1)} / 5</strong><Stars rating={data.average}/><span>Based on {data.total} {data.total===1?'review':'reviews'}</span></>:<span>No reviews yet. Be the first to share your experience.</span>}</div>}
 <div className="review-layout"><form onSubmit={submit} className="review-form"><h3>{mine?'Your review':'Leave a review'}</h3><label>Display name<input name="name" value={form.name} onChange={change} required maxLength={25000} placeholder="A name or nickname" autoComplete="off"/></label><fieldset><legend>Your rating</legend><div className="rating-options">{[1,2,3,4,5].map(n=><label key={n} className={n<=form.rating?'selected':''}><input type="radio" name="rating" value={n} checked={form.rating===n} onChange={()=>setForm(f=>({...f,rating:n}))} required aria-label={`${n} ${n===1?'star':'stars'}`}/><span aria-hidden="true">★</span></label>)}</div></fieldset><label>Your comment<textarea name="comment" value={form.comment} onChange={change} required minLength={10} maxLength={25000} rows={6} placeholder="What was helpful? What could be better?" aria-describedby="review-count"/></label><small id="review-count">{form.comment.length.toLocaleString()} / 25,000 characters</small><div className="review-trap" aria-hidden="true"><label>Leave this empty<input name="website" value={form.website} onChange={change} tabIndex={-1} autoComplete="off"/></label></div><label className="review-consent"><input type="checkbox" name="consent" checked={form.consent} onChange={change} required/>I understand my display name, rating and comment will be public.</label><p className="review-note">Please keep private details out of your comment. One review per browser identity; you can update or remove it here using the same browser. Clearing browser data may remove that access. Reviews are visitor submissions, not verified purchases.</p>{!identityReady&&!loading&&<button type="button" className="secondary-button" onClick={()=>setRevision(x=>x+1)}>Reconnect to reviews</button>}<button className="primary-button" disabled={busy||!identityReady}>{busy?'Saving…':mine?'Update my review':'Publish my review'}</button>{mine&&!confirmDelete&&<button type="button" className="secondary-button" onClick={()=>setConfirmDelete(true)} disabled={busy}>Remove my review</button>}{confirmDelete&&<div><p>Remove your public review?</p><button type="button" className="secondary-button" onClick={remove} disabled={busy}>Yes, remove it</button><button type="button" className="secondary-button" onClick={()=>setConfirmDelete(false)}>Keep review</button></div>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error-banner">{error}</p>}</form>
 <div aria-live="polite" aria-busy={loading}><h3>Community experiences</h3>{loading&&<p>Loading reviews…</p>}{!loading&&data?.reviews.map(review=><article className="review-card" key={review.publicId}><header><strong>{review.name}</strong><Stars rating={review.rating}/></header><time dateTime={review.createdAt}>{new Date(review.createdAt).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}</time><p>{review.comment}</p></article>)}{!loading&&data?.total>12&&<nav aria-label="Review pages" className="review-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.ceil(data.total/12)}</span><button disabled={page*12>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}{!loading&&!data&&<button className="secondary-button" onClick={()=>{setRevision(x=>x+1);}}>Try loading reviews again</button>}</div></div></section>;
}
